on:
  push:
    branches:
      - main

jobs:
  tag_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          for TAG in `make determine-changes`
          do
              git tag $TAG.$GITHUB_RUN_NUMBER.cd
          done
          git push origin --tags
